# **1. Data Collection**

### **1.1 Load Data**

In [ ]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

file_path = "/content/drive/MyDrive/Major Project/0819_UkraineCombinedTweetsDeduped.csv"
df = pd.read_csv(file_path)

Mounted at /content/drive

In [ ]:
df

,Unnamed: 0,userid,username,acctdesc,location,following,followers,totaltweets,usercreatedts,tweetid,...,original_tweet_userid,original_tweet_username,in_reply_to_status_id,in_reply_to_user_id,in_reply_to_screen_name,is_quote_status,quoted_status_id,quoted_status_userid,quoted_status_username,extractedts
0,0,173212647,JoeMokolobetsi,Yeshua Hamashiach is THE answer | Romans 10:9-...,Afrika Borwa,219,197,4789,2010-07-31 19:09:22.000000,1560416252937617411,...,0,NaN,0,0,NaN,False,0,0,NaN,2022-08-19 08:07:26.836769
1,1,335041409,XclusivasPuebla,Somos el periódico #ExclusivasPuebla| Investi...,"Puebla, México",1419,6402,70267,2011-07-14 02:02:24.000000,1560416256179707904,...,0,NaN,0,0,NaN,False,0,0,NaN,2022-08-19 07:51:50.523048
2,2,1512400441103032323,ShelterAnimalUA,Shelter for abandoned dogs and cats. 1400 dogs...,Ukraine,782,109,1198,2022-04-08 12:02:47.000000,1560416257752666113,...,0,NaN,0,0,NaN,False,0,0,NaN,2022-08-19 05:12:06.194216
3,3,1356632630662430722,DogandCatHelpe1,Shelter for abandoned dogs and cats. 1400 dogs...,Ukraine,5,39,690,2021-02-02 15:57:12.000000,1560416257790382081,...,0,NaN,0,0,NaN,False,0,0,NaN,2022-08-19 11:22:26.824532
4,4,20297125,ElMananaOnline,Las mejores noticias de los dos Laredos y el m...,Nuevo Laredo,2269,17978,56188,2009-02-07 06:32:49.000000,1560416257937051648,...,0,NaN,0,0,NaN,False,0,0,NaN,2022-08-19 11:52:29.448634
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47989,47989,1553460900727853056,Ksana_tt_,"Рада всім українцям, бо #УкрТві неймовірний💙💛",🇺🇦,237,157,51,2022-07-30 19:22:33.000000,1560778594703577090,...,0,NaN,0,0,NaN,True,1560773862756851712,1593157274,igorlachenkov,2022-08-20 01:34:19.026497
47990,47990,132907794,krishtopa,Процедурно згенерований мешканець Всесвіту,Львів/ Сєвєродонецьк,687,488,23608,2010-04-14 14:01:46.000000,1560778614169288705,...,0,NaN,1560778126619299840,34132596,dosnostalgic,False,0,0,NaN,2022-08-20 01:33:03.111239
47991,47991,14445094,El_Ciudadano,https://t.co/hF7jqSE6Tk medio de comunicación ...,Santiago de Chile,71965,553230,226276,2008-04-19 17:43:02.000000,1560778618208342016,...,0,NaN,0,0,NaN,False,0,0,NaN,2022-08-20 00:52:50.050159
47992,47992,1382090090059534336,ElCiudadano_Mx,Prensa libertaria en Puebla ¿Tienes alguna den...,"Puebla, México",461,1109,30631,2021-04-13 21:57:41.000000,1560778619428999168,...,0,NaN,0,0,NaN,False,0,0,NaN,2022-08-20 00:52:50.040182
47993,47993,243266116,TheBrianHopkins,Award winning internet writer. Businessman. Su...,"Atlanta, GA",1423,3325,1904,2011-01-26 17:36:18.000000,1560778628056637441,...,0,NaN,0,0,NaN,False,0,0,NaN,2022-08-20 00:37:50.546178

# **2. Data Preprocessing**

### **2.1 Explore Data**

In [ ]:
print("Column Names:\n\n", df.columns)

Column Names:

 Index(['Unnamed: 0', 'userid', 'username', 'acctdesc', 'location', 'following',
       'followers', 'totaltweets', 'usercreatedts', 'tweetid',
       'tweetcreatedts', 'retweetcount', 'text', 'hashtags', 'language',
       'coordinates', 'favorite_count', 'is_retweet', 'original_tweet_id',
       'original_tweet_userid', 'original_tweet_username',
       'in_reply_to_status_id', 'in_reply_to_user_id',
       'in_reply_to_screen_name', 'is_quote_status', 'quoted_status_id',
       'quoted_status_userid', 'quoted_status_username', 'extractedts'],
      dtype='object')

In [ ]:
print("Dataset Information:\n"); df.info()

Dataset Information:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47994 entries, 0 to 47993
Data columns (total 29 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unnamed: 0               47994 non-null  int64
 1   userid                   47994 non-null  int64
 2   username                 47994 non-null  object
 3   acctdesc                 43037 non-null  object
 4   location                 31703 non-null  object
 5   following                47994 non-null  int64
 6   followers                47994 non-null  int64
 7   totaltweets              47994 non-null  int64
 8   usercreatedts            47994 non-null  object
 9   tweetid                  47994 non-null  int64
 10  tweetcreatedts           47994 non-null  object
 11  retweetcount             47994 non-null  int64
 12  text                     47994 non-null  object
 13  hashtags                 47994 non-null  object
 14  language                 47994 non-null  object
 15  coordinates              189 non-null    object
 16  favorite_count           47994 non-null  int64
 17  is_retweet               47994 non-null  bool
 18  original_tweet_id        47994 non-null  int64
 19  original_tweet_userid    47994 non-null  int64
 20  original_tweet_username  0 non-null      float64
 21  in_reply_to_status_id    47994 non-null  int64
 22  in_reply_to_user_id      47994 non-null  int64
 23  in_reply_to_screen_name  13240 non-null  object
 24  is_quote_status          47994 non-null  bool
 25  quoted_status_id         47994 non-null  int64
 26  quoted_status_userid     47994 non-null  int64
 27  quoted_status_username   7089 non-null   object
 28  extractedts              47994 non-null  object
dtypes: bool(2), float64(1), int64(14), object(12)
memory usage: 10.0+ MB

In [ ]:
columns = ['text', 'language', 'tweetcreatedts', 'retweetcount', 'favorite_count', 'hashtags', 'extractedts']

df_early = df[columns].copy()
df_early.head(10)

,text,language,tweetcreatedts,retweetcount,favorite_count,hashtags,extractedts
0,Dear vaccine advocate\n\nDo take the COVID19 m...,en,2022-08-19 00:00:00,0,0,"[{'text': 'Pfizer', 'indices': [189, 196]}, {'...",2022-08-19 08:07:26.836769
1,#Mundo \n\nAl menos 6 muertos y 16 heridos en ...,es,2022-08-19 00:00:01,0,0,"[{'text': 'Mundo', 'indices': [0, 6]}, {'text'...",2022-08-19 07:51:50.523048
2,"Animal shelter Dogs and Cats, we need your hel...",en,2022-08-19 00:00:01,0,1,"[{'text': 'Ukraine', 'indices': [189, 197]}, {...",2022-08-19 05:12:06.194216
3,"Welcome to our shelter!\nLocated in Ukraine, K...",en,2022-08-19 00:00:01,0,2,"[{'text': 'Ukraine', 'indices': [194, 202]}, {...",2022-08-19 11:22:26.824532
4,"Tensión, debido a que #Rusia sigue en pie en l...",es,2022-08-19 00:00:01,0,0,"[{'text': 'Rusia', 'indices': [22, 28]}, {'tex...",2022-08-19 11:52:29.448634
5,👇 Good news you may have missed: First @WFP sh...,en,2022-08-19 00:00:01,0,0,"[{'text': 'humanitarian', 'indices': [66, 79]}...",2022-08-19 05:12:06.096707
6,Opinion: The Ukraine war is also being fought ...,en,2022-08-19 00:00:03,0,0,"[{'text': 'Ukraine', 'indices': [68, 76]}, {'t...",2022-08-19 08:02:53.510769
7,"Ale Fuck tèt ou, Putin!\n(Haitian Creole)\n\n#...",ht,2022-08-19 00:00:04,0,0,"[{'text': 'IStandWithUkraine', 'indices': [42,...",2022-08-19 08:02:53.387825
8,"Ethereum's spot setup looks grim, but derivati...",en,2022-08-19 00:00:04,0,1,"[{'text': 'cryptocurrency', 'indices': [79, 94...",2022-08-19 05:12:06.018650
9,"Artículo de #JeffreyDSachs. 👉 ""#Biden está lle...",es,2022-08-19 00:00:05,0,0,"[{'text': 'JeffreyDSachs', 'indices': [12, 26]...",2022-08-19 11:22:26.795610

### **2.2 Date Range**

In [ ]:
print("Maximum Date:", df_early['extractedts'].min())
print("Minimum Date:", df_early['extractedts'].max())

Maximum Date: 2022-08-19 00:16:55.258603
Minimum Date: 2022-08-20 01:35:11.291583

### **2.3 Timestamp Feature Extraction**

In [ ]:
df_early.rename(columns={'extractedts': 'timestamp'}, inplace=True)
df_early['timestamp'] = pd.to_datetime(df_early['timestamp'])
df_early['date'] = df_early['timestamp'].dt.date
df_early['hour'] = df_early['timestamp'].dt.hour
df_early['phase'] = 'Early War'
df_early[['timestamp', 'date', 'hour', 'phase']].head(10)

                   timestamp        date  hour      phase
0 2022-08-19 08:07:26.836769  2022-08-19     8  Early War
1 2022-08-19 07:51:50.523048  2022-08-19     7  Early War
2 2022-08-19 05:12:06.194216  2022-08-19     5  Early War
3 2022-08-19 11:22:26.824532  2022-08-19    11  Early War
4 2022-08-19 11:52:29.448634  2022-08-19    11  Early War
5 2022-08-19 05:12:06.096707  2022-08-19     5  Early War
6 2022-08-19 08:02:53.510769  2022-08-19     8  Early War
7 2022-08-19 08:02:53.387825  2022-08-19     8  Early War
8 2022-08-19 05:12:06.018650  2022-08-19     5  Early War
9 2022-08-19 11:22:26.795610  2022-08-19    11  Early War

### **2.4 Data Cleaning**

In [ ]:
import re

def clean_tweet(text):
    text = str(text).lower()
    text = re.sub(r"http\S+|www\S+", "", text)
    text = re.sub(r"@\w+", "", text)
    text = re.sub(r"#", "", text)
    text = re.sub(r"\d+", "", text)
    text = re.sub(r"[^\w\s]", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

df_early['clean_text'] = df_early['text'].apply(clean_tweet)
df_early.drop_duplicates(subset='clean_text', inplace=True)
df_early.dropna(subset=['clean_text'], inplace=True)
df_early = df_early[df_early['clean_text'].str.strip() != '']
df_early.reset_index(drop=True, inplace=True)

print("\nTotal Tweets:", len(df_early))
df_early[['clean_text']].head(10)

Total Tweets: 42214

                                          clean_text
0  dear vaccine advocate do take the covid mrna s...
1  mundo al menos muertos y heridos en bombardeo ...
2  animal shelter dogs and cats we need your help...
3  welcome to our shelter located in ukraine kyiv...
4  tensión debido a que rusia sigue en pie en la ...
5  good news you may have missed first shipment o...
6  opinion the ukraine war is also being fought o...
7  ale fuck tèt ou putin haitian creole istandwit...
8  ethereums spot setup looks grim but derivative...
9  artículo de jeffreydsachs biden está llevando ...

### **2.5 Language Mapping**

In [ ]:
lang_map = {
    'en': 'English', 'und': 'Undefined', 'de': 'German', 'uk': 'Ukrainian', 'fr': 'French', 'it': 'Italian',
    'es': 'Spanish', 'ru': 'Russian', 'ja': 'Japanese', 'tr': 'Turkish', 'pt': 'Portuguese', 'zh': 'Chinese',
    'in': 'Indonesian', 'nl': 'Dutch', 'pl': 'Polish', 'el': 'Greek', 'hi': 'Hindi', 'ar': 'Arabic',
    'fi': 'Finnish', 'ro': 'Romanian', 'no': 'Norwegian', 'sv': 'Swedish', 'et': 'Estonian', 'da': 'Danish',
    'ca': 'Catalan', 'vi': 'Vietnamese', 'fa': 'Persian', 'th': 'Thai', 'ur': 'Urdu', 'ht': 'Haitian Creole',
    'tl': 'Tagalog', 'cs': 'Czech', 'iw': 'Hebrew', 'bn': 'Bengali', 'ta': 'Tamil', 'lv': 'Latvian',
    'eu': 'Basque', 'ko': 'Korean', 'sl': 'Slovenian', 'bg': 'Bulgarian', 'gu': 'Gujarati', 'ka': 'Georgian',
    'te': 'Telugu', 'lt': 'Lithuanian', 'kn': 'Kannada', 'sr': 'Serbian', 'is': 'Icelandic', 'cy': 'Welsh',
    'ml': 'Malayalam', 'mr': 'Marathi', 'am': 'Amharic', 'my': 'Burmese', 'or': 'Odia', 'hu': 'Hungarian',
    'pa': 'Punjabi', 'ne': 'Nepali', 'hy': 'Armenian', 'sd': 'Sindhi', 'ps': 'Pashto'}

df_early['language_full'] = df_early['language'].map(lang_map)
lang_counts = (df_early.groupby(['language', 'language_full']).size().reset_index(name='count').sort_values(by='count', ascending=False))
lang_counts['proportion(%)'] = (lang_counts['count'] / lang_counts['count'].sum() * 100).round(2)
lang_counts

   language   language_full  count  proportion(%)
10       en         English  21003          49.75
8        de          German   4065           9.63
54       uk       Ukrainian   3121           7.39
55      und       Undefined   2702           6.40
16       fr          French   2112           5.00
24       it         Italian   1795           4.25
11       es         Spanish   1547           3.66
44       ru         Russian   1420           3.36
26       ja        Japanese    449           1.06
53       tr         Turkish    374           0.89
42       pt      Portuguese    333           0.79
58       zh         Chinese    261           0.62
22       in      Indonesian    237           0.56
36       nl           Dutch    217           0.51
40       pl          Polish    216           0.51
9        el           Greek    177           0.42
18       hi           Hindi    154           0.36
1        ar          Arabic    143           0.34
15       fi         Finnish    130           0.31
43       ro        Romanian    109           0.26
48       sv         Swedish    101           0.24
37       no       Norwegian    100           0.24
12       et        Estonian     91           0.22
4        ca         Catalan     88           0.21
57       vi      Vietnamese     86           0.20
14       fa         Persian     83           0.20
7        da          Danish     83           0.20
51       th            Thai     79           0.19
56       ur            Urdu     76           0.18
19       ht  Haitian Creole     74           0.18
52       tl         Tagalog     71           0.17
25       iw          Hebrew     68           0.16
5        cs           Czech     63           0.15
3        bn         Bengali     60           0.14
49       ta           Tamil     58           0.14
13       eu          Basque     54           0.13
31       lv         Latvian     52           0.12
29       ko          Korean     49           0.12
46       sl       Slovenian     33           0.08
17       gu        Gujarati     31           0.07
2        bg       Bulgarian     31           0.07
27       ka        Georgian     30           0.07
30       lt      Lithuanian     29           0.07
50       te          Telugu     29           0.07
28       kn         Kannada     27           0.06
47       sr         Serbian     25           0.06
23       is       Icelandic     17           0.04
32       ml       Malayalam     14           0.03
6        cy           Welsh     12           0.03
33       mr         Marathi     10           0.02
0        am         Amharic      6           0.01
34       my         Burmese      4           0.01
20       hu       Hungarian      4           0.01
38       or            Odia      4           0.01
39       pa         Punjabi      3           0.01
21       hy        Armenian      1           0.00
35       ne          Nepali      1           0.00
41       ps          Pashto      1           0.00
45       sd          Sindhi      1           0.00

# **3. Sentiment Analysis**

### **3.1 Sentiment Classification Pipeline**

In [ ]:
from transformers import pipeline

sentiment_model = pipeline(
    "sentiment-analysis",
    model="cardiffnlp/twitter-xlm-roberta-base-sentiment",
    device=0)

config.json:   0%|          | 0.00/841 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.11G [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.11G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

XLMRobertaForSequenceClassification LOAD REPORT from: cardiffnlp/twitter-xlm-roberta-base-sentiment
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

special_tokens_map.json:   0%|          | 0.00/150 [00:00<?, ?B/s]

In [ ]:
texts = df_early['clean_text'].astype(str).str.slice(0,512).tolist()

def get_sentiment_batch(texts, batch_size=32):
    results = []

    for i in range(0, len(texts), batch_size):
        batch = texts[i:i+batch_size]
        batch_results = sentiment_model(batch)
        results.extend(batch_results)

    return results

sentiment_results = get_sentiment_batch(texts, batch_size=32)

sentiments = []
sent_scores = []

for result in sentiment_results:
    sentiments.append(result['label'])
    sent_scores.append(result['score'])

df_early['sentiment'] = sentiments
df_early['sentiment_score'] = sent_scores
df_early[['clean_text','sentiment','sentiment_score']].head(10)

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

,clean_text,sentiment,sentiment_score
0,dear vaccine advocate do take the covid mrna s...,negative,0.648191
1,mundo al menos muertos y heridos en bombardeo ...,negative,0.762223
2,animal shelter dogs and cats we need your help...,neutral,0.521743
3,welcome to our shelter located in ukraine kyiv...,neutral,0.518396
4,tensión debido a que rusia sigue en pie en la ...,negative,0.939731
5,good news you may have missed first shipment o...,negative,0.495176
6,opinion the ukraine war is also being fought o...,negative,0.681396
7,ale fuck tèt ou putin haitian creole istandwit...,negative,0.682447
8,ethereums spot setup looks grim but derivative...,negative,0.665471
9,artículo de jeffreydsachs biden está llevando ...,negative,0.922263

### **3.2 Sentiment Summary**

In [ ]:
sentiment_summary = (df_early['sentiment'].value_counts().reset_index())
sentiment_summary['proportion(%)'] = (sentiment_summary['count'] / sentiment_summary['count'].sum() * 100).round(2)

sentiment_summary

  sentiment  count  proportion(%)
0  negative  26365          62.46
1   neutral  12215          28.94
2  positive   3634           8.61

# **4. Emotion Analysis**

### **4.1 Emotion Classification Pipeline**

In [ ]:
emotion_model = pipeline(
    "zero-shot-classification",
    model="MoritzLaurer/mDeBERTa-v3-base-xnli-multilingual-nli-2mil7",
    device=0)

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/558M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

DebertaV2ForSequenceClassification LOAD REPORT from: MoritzLaurer/mDeBERTa-v3-base-xnli-multilingual-nli-2mil7
Key                             | Status     |  |
--------------------------------+------------+--+-
deberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/467 [00:00<?, ?B/s]

spm.model:   0%|          | 0.00/4.31M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/16.3M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/23.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/173 [00:00<?, ?B/s]

In [ ]:
candidate_labels = ["joy", "sadness", "anger", "fear", "love", "surprise"]

def get_emotions_batch(texts, batch_size=64):
    results = []

    for i in range(0, len(texts), batch_size):
        batch = texts[i:i+batch_size]
        outputs = emotion_model(batch, candidate_labels)
        results.extend(outputs)

    return results

emotion_results = get_emotions_batch(texts, batch_size=64)

emotions = []
emotion_scores = []

for result in emotion_results:
    emotions.append(result['labels'][0])
    emotion_scores.append(result['scores'][0])

df_early['emotion'] = emotions
df_early['emotion_score'] = emotion_scores
df_early[['clean_text', 'emotion', 'emotion_score']].head(10)

                                          clean_text   emotion  emotion_score
0  dear vaccine advocate do take the covid mrna s...   sadness       0.501011
1  mundo al menos muertos y heridos en bombardeo ...      fear       0.326245
2  animal shelter dogs and cats we need your help...  surprise       0.343419
3  welcome to our shelter located in ukraine kyiv...  surprise       0.325446
4  tensión debido a que rusia sigue en pie en la ...     anger       0.872050
5  good news you may have missed first shipment o...       joy       0.352644
6  opinion the ukraine war is also being fought o...     anger       0.787237
7  ale fuck tèt ou putin haitian creole istandwit...     anger       0.707322
8  ethereums spot setup looks grim but derivative...   sadness       0.564533
9  artículo de jeffreydsachs biden está llevando ...   sadness       0.386619

### **4.2 Emotion Summary**

In [ ]:
emotion_summary = (df_early['emotion'].value_counts().reset_index())
emotion_summary.columns = ['emotion', 'count']
emotion_summary['proportion(%)'] = (emotion_summary['count'] / emotion_summary['count'].sum() * 100).round(2)

emotion_summary

    emotion  count  proportion(%)
0     anger  20529          48.63
1  surprise   7260          17.20
2   sadness   6234          14.77
3       joy   3965           9.39
4      fear   3443           8.16
5      love    783           1.85

# **5. Save Clean Data**

In [ ]:
clean_dataset = ['text', 'clean_text', 'language', 'language_full', 'sentiment', 'sentiment_score', 'emotion', 'emotion_score', 'timestamp', 'date', 'hour', 'tweetcreatedts', 'retweetcount', 'favorite_count', 'hashtags', 'phase']

df_early[clean_dataset].to_csv("/content/drive/My Drive/Major Project/clean_early_war_dataset.csv", index=False)

# **6. Import Clean Data**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

file_path = "/content/drive/My Drive/Major Project/clean_early_war_dataset.csv"
df_early = pd.read_csv(file_path)

Mounted at /content/drive

In [ ]:
df_early

,text,clean_text,language,language_full,sentiment,sentiment_score,emotion,emotion_score,timestamp,date,hour,tweetcreatedts,retweetcount,favorite_count,hashtags,phase
0,Dear vaccine advocate\n\nDo take the COVID19 m...,dear vaccine advocate do take the covid mrna s...,en,English,negative,0.648191,sadness,0.501011,2022-08-19 08:07:26.836769,2022-08-19,8,2022-08-19 00:00:00,0,0,"[{'text': 'Pfizer', 'indices': [189, 196]}, {'...",Early War
1,#Mundo \n\nAl menos 6 muertos y 16 heridos en ...,mundo al menos muertos y heridos en bombardeo ...,es,Spanish,negative,0.762223,fear,0.326245,2022-08-19 07:51:50.523048,2022-08-19,7,2022-08-19 00:00:01,0,0,"[{'text': 'Mundo', 'indices': [0, 6]}, {'text'...",Early War
2,"Animal shelter Dogs and Cats, we need your hel...",animal shelter dogs and cats we need your help...,en,English,neutral,0.521743,surprise,0.343419,2022-08-19 05:12:06.194216,2022-08-19,5,2022-08-19 00:00:01,0,1,"[{'text': 'Ukraine', 'indices': [189, 197]}, {...",Early War
3,"Welcome to our shelter!\nLocated in Ukraine, K...",welcome to our shelter located in ukraine kyiv...,en,English,neutral,0.518396,surprise,0.325446,2022-08-19 11:22:26.824532,2022-08-19,11,2022-08-19 00:00:01,0,2,"[{'text': 'Ukraine', 'indices': [194, 202]}, {...",Early War
4,"Tensión, debido a que #Rusia sigue en pie en l...",tensión debido a que rusia sigue en pie en la ...,es,Spanish,negative,0.939731,anger,0.872050,2022-08-19 11:52:29.448634,2022-08-19,11,2022-08-19 00:00:01,0,0,"[{'text': 'Rusia', 'indices': [22, 28]}, {'tex...",Early War
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42209,Не про мене тому що я ніколи не наважусь\n(на ...,не про мене тому що я ніколи не наважусь на щастя,uk,Ukrainian,neutral,0.481626,anger,0.384255,2022-08-20 01:33:03.137550,2022-08-20,1,2022-08-19 23:59:46,0,0,[],Early War
42210,"Everything as usual, just another russian gove...",everything as usual just another russian gover...,en,English,negative,0.905897,fear,0.355666,2022-08-20 01:34:19.026497,2022-08-20,1,2022-08-19 23:59:49,2,4,"[{'text': 'RussiaIsATerroristState', 'indices'...",Early War
42211,@dosnostalgic twisted firestarter!,twisted firestarter,en,English,negative,0.619426,surprise,0.353891,2022-08-20 01:33:03.111239,2022-08-20,1,2022-08-19 23:59:54,0,2,[],Early War
42212,La ruleta Ep. 7: #Ucrania: Presidente Zelensky...,la ruleta ep ucrania presidente zelensky el hé...,es,Spanish,negative,0.822688,anger,0.422493,2022-08-20 00:52:50.050159,2022-08-20,0,2022-08-19 23:59:55,0,0,"[{'text': 'Ucrania', 'indices': [17, 25]}]",Early War
42213,When people say the US was in better shape whi...,when people say the us was in better shape whi...,en,English,negative,0.538731,sadness,0.348344,2022-08-20 00:37:50.546178,2022-08-20,0,2022-08-19 23:59:57,3,12,"[{'text': 'Biden', 'indices': [151, 157]}, {'t...",Early War