# **1. Data Collection**

### **1.1 Load Data**

In [ ]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

file_path = "/content/drive/My Drive/Major Project/20230607_UkraineCombinedTweetsDeduped.csv"
df = pd.read_csv(file_path)

Mounted at /content/drive

In [ ]:
df

,Unnamed: 0,userid,username,acctdesc,location,following,followers,totaltweets,usercreatedts,tweetid,...,original_tweet_userid,original_tweet_username,in_reply_to_status_id,in_reply_to_user_id,in_reply_to_screen_name,is_quote_status,quoted_status_id,quoted_status_userid,quoted_status_username,extractedts
0,192749,1273218547846729729,ArabNewsfr,Arab News en français est l’édition francophon...,Riyad,83,82242,91258,2020-06-17 11:39:14,1666233533885734912,...,0,NaN,0,0,NaN,False,0,0,NaN,2023-06-07 00:23:08.483217
1,192750,22451879,olealsaker,Norwegian Berliner | Journalist @dwnews | BLN ...,"Berlin, Germany",694,636,2346,2009-03-02 04:43:32,1666233543091970050,...,0,NaN,0,0,NaN,False,0,0,NaN,2023-06-07 00:23:08.478047
2,192751,1629072785103372288,najy_221,NaN,NaN,498,129,5726,2023-02-24 10:57:42,1666233637199552516,...,0,NaN,0,0,NaN,False,0,0,NaN,2023-06-07 00:23:08.472855
3,192752,1560992437128110080,UnPirater,https://t.co/IFwCquyDQu est une interface Web ...,France,8,1692,20390,2022-08-20 14:09:39,1666233648461529089,...,0,NaN,0,0,NaN,False,0,0,NaN,2023-06-07 00:23:08.467704
4,192753,1498401220142247936,hardingmennyfx,💯pathfinder to recovery 🔋,NaN,0,36,215,2022-02-28 20:54:45,1666233739049828352,...,0,NaN,0,0,NaN,False,0,0,NaN,2023-06-07 00:23:08.462562
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24965,217714,1306197774,JohnLocker4,"Why should I fear death?\nIf I am, then death ...",planet Earth,4038,2125,98748,2013-03-27 01:55:26,1666595885827125248,...,0,NaN,0,0,NaN,False,0,0,NaN,2023-06-08 02:33:35.776122
24966,217715,1658112476100132866,YitselMAR,NaN,NaN,7,1,586,2023-05-15 14:10:30,1666595886795767810,...,741705695993569280,CanalCaribeCuba,0,0,NaN,False,0,0,NaN,2023-06-08 00:09:47.670528
24967,217716,1551723713409826817,13_cof,Centro Oftalmológico 13 de abril,NaN,181,140,23001,2022-07-26 00:19:51,1666595887802400770,...,1065603451491663872,MoraYuniesky,0,0,NaN,False,0,0,NaN,2023-06-08 00:09:47.664898
24968,217717,1666560917532753923,YusdenkiL,NaN,NaN,35,0,4,2023-06-07 21:42:25,1666595891938045952,...,1025037163291914240,DiazCanelB,0,0,NaN,True,1666436487523581952,0,NaN,2023-06-08 00:09:47.659283
24969,217718,1519436803450843137,viton_perez,"Cubana, Artemiseña, orgullosa de mi terruño y ...",Cuba,518,1160,18977,2022-04-27 22:03:10,1666595893741510657,...,1072261406521724928,DrRobertoMOjeda,0,0,NaN,False,0,0,NaN,2023-06-08 00:09:47.653605

# **2. Data Preprocessing**

### **2.1 Explore Data**

In [ ]:
print("Column Names:\n\n", df.columns)

Column Names:

 Index(['Unnamed: 0', 'userid', 'username', 'acctdesc', 'location', 'following',
       'followers', 'totaltweets', 'usercreatedts', 'tweetid',
       'tweetcreatedts', 'retweetcount', 'text', 'hashtags', 'language',
       'coordinates', 'favorite_count', 'is_retweet', 'original_tweet_id',
       'original_tweet_userid', 'original_tweet_username',
       'in_reply_to_status_id', 'in_reply_to_user_id',
       'in_reply_to_screen_name', 'is_quote_status', 'quoted_status_id',
       'quoted_status_userid', 'quoted_status_username', 'extractedts'],
      dtype='object')

In [ ]:
print("Dataset Information:\n"); df.info()

Dataset Information:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24970 entries, 0 to 24969
Data columns (total 29 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unnamed: 0               24970 non-null  int64
 1   userid                   24970 non-null  int64
 2   username                 24970 non-null  object
 3   acctdesc                 18861 non-null  object
 4   location                 13866 non-null  object
 5   following                24970 non-null  int64
 6   followers                24970 non-null  int64
 7   totaltweets              24970 non-null  int64
 8   usercreatedts            24970 non-null  object
 9   tweetid                  24970 non-null  int64
 10  tweetcreatedts           24970 non-null  object
 11  retweetcount             24970 non-null  int64
 12  text                     24970 non-null  object
 13  hashtags                 24970 non-null  object
 14  language                 24970 non-null  object
 15  coordinates              31 non-null     object
 16  favorite_count           24970 non-null  int64
 17  is_retweet               24970 non-null  bool
 18  original_tweet_id        24970 non-null  int64
 19  original_tweet_userid    24970 non-null  int64
 20  original_tweet_username  14354 non-null  object
 21  in_reply_to_status_id    24970 non-null  int64
 22  in_reply_to_user_id      24970 non-null  int64
 23  in_reply_to_screen_name  2877 non-null   object
 24  is_quote_status          24970 non-null  bool
 25  quoted_status_id         24970 non-null  int64
 26  quoted_status_userid     24970 non-null  int64
 27  quoted_status_username   1717 non-null   object
 28  extractedts              24970 non-null  object
dtypes: bool(2), int64(14), object(13)
memory usage: 5.2+ MB

In [ ]:
columns = ['text', 'language', 'tweetcreatedts', 'retweetcount', 'favorite_count', 'hashtags', 'extractedts']

df_later = df[columns].copy()
df_later.head(10)

,text,language,tweetcreatedts,retweetcount,favorite_count,hashtags,extractedts
0,L'#Ukraine et la #Russie présentent cette sema...,fr,2023-06-07 00:00:06,0,2,"[{'text': 'Ukraine', 'indices': [2, 10]}, {'te...",2023-06-07 00:23:08.483217
1,I had the pleasure of talking to National Secu...,en,2023-06-07 00:00:08,0,0,"[{'text': 'Kakhovka', 'indices': [85, 94]}, {'...",2023-06-07 00:23:08.478047
2,Possible Consequences of Kosovo &amp; Serbia T...,ca,2023-06-07 00:00:30,0,0,"[{'text': 'Russia', 'indices': [54, 61]}, {'te...",2023-06-07 00:23:08.472855
3,https://t.co/qMZLQEQWjs\nhttps://t.co/TfXdd1Kp...,und,2023-06-07 00:00:33,0,0,"[{'text': 'twitter', 'indices': [73, 81]}, {'t...",2023-06-07 00:23:08.467704
4,if you are still having issues withdrawing you...,en,2023-06-07 00:00:55,0,0,"[{'text': 'kicurency', 'indices': [109, 119]},...",2023-06-07 00:23:08.462562
5,Today : Ukraine Missile DESTROY Russian target...,en,2023-06-07 00:01:02,0,0,"[{'text': 'Canada', 'indices': [94, 101]}, {'t...",2023-06-07 00:23:08.457361
6,"Em outubro, #Zelensky afirmou que os russos ti...",pt,2023-06-07 00:01:06,0,0,"[{'text': 'Zelensky', 'indices': [12, 21]}, {'...",2023-06-07 00:58:47.402764
7,SWEDISH NATIONAL DAY AND THE FOREST MAY NOT BE...,en,2023-06-07 00:01:12,0,0,"[{'text': 'twitch', 'indices': [114, 121]}, {'...",2023-06-07 00:23:08.447065
8,Antwort auf #dpa-Chef : Die dpa meldet um 3.39...,de,2023-06-07 00:01:14,0,0,"[{'text': 'dpa', 'indices': [12, 16]}, {'text'...",2023-06-07 00:23:08.441884
9,Reminder to all our #Vatniks and #Russia suppo...,en,2023-06-07 00:01:50,0,0,"[{'text': 'Vatniks', 'indices': [20, 28]}, {'t...",2023-06-07 00:23:08.436738

### **2.2 Date Range**

In [ ]:
print("Maximum Date:", df_later['extractedts'].min())
print("Minimum Date:", df_later['extractedts'].max())

Maximum Date: 2023-06-07 00:23:07.907874
Minimum Date: 2023-06-08 02:33:39.204289

### **2.3 Timestamp Feature Extraction**

In [ ]:
df_later.rename(columns={'extractedts': 'timestamp'}, inplace=True)
df_later['timestamp'] = pd.to_datetime(df_later['timestamp'])
df_later['date'] = df_later['timestamp'].dt.date
df_later['hour'] = df_later['timestamp'].dt.hour
df_later['phase'] = 'Later War'
df_later[['timestamp', 'date', 'hour', 'phase']].head(10)

                   timestamp        date  hour      phase
0 2023-06-07 00:23:08.483217  2023-06-07     0  Later War
1 2023-06-07 00:23:08.478047  2023-06-07     0  Later War
2 2023-06-07 00:23:08.472855  2023-06-07     0  Later War
3 2023-06-07 00:23:08.467704  2023-06-07     0  Later War
4 2023-06-07 00:23:08.462562  2023-06-07     0  Later War
5 2023-06-07 00:23:08.457361  2023-06-07     0  Later War
6 2023-06-07 00:58:47.402764  2023-06-07     0  Later War
7 2023-06-07 00:23:08.447065  2023-06-07     0  Later War
8 2023-06-07 00:23:08.441884  2023-06-07     0  Later War
9 2023-06-07 00:23:08.436738  2023-06-07     0  Later War

### **2.4 Data Cleaning**

In [ ]:
import re

def clean_tweet(text):
    text = str(text).lower()
    text = re.sub(r"http\S+|www\S+", "", text)
    text = re.sub(r"@\w+", "", text)
    text = re.sub(r"#", "", text)
    text = re.sub(r"\d+", "", text)
    text = re.sub(r"[^\w\s]", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

df_later['clean_text'] = df_later['text'].apply(clean_tweet)
df_later.drop_duplicates(subset='clean_text', inplace=True)
df_later.dropna(subset=['clean_text'], inplace=True)
df_later = df_later[df_later['clean_text'].str.strip() != '']
df_later.reset_index(drop=True, inplace=True)

print("\nTotal Tweets:", len(df_later))
df_later[['clean_text']].head(10)

Total Tweets: 11419

                                          clean_text
0  lukraine et la russie présentent cette semaine...
1  i had the pleasure of talking to national secu...
2  possible consequences of kosovo amp serbia ten...
3  twitter facebook metaverse trump joebiden usa ...
4  if you are still having issues withdrawing you...
5  today ukraine missile destroy russian target f...
6  em outubro zelensky afirmou que os russos tinh...
7  swedish national day and the forest may not be...
8  antwort auf dpachef die dpa meldet um uhr un n...
9  reminder to all our vatniks and russia support...

### **2.5 Language Mapping**

In [ ]:
lang_map = {
    'en': 'English', 'es': 'Spanish', 'und': 'Undefined', 'de': 'German', 'fr': 'French', 'it': 'Italian',
    'uk': 'Ukrainian', 'ru': 'Russian', 'in': 'Indonesian', 'nl': 'Dutch', 'pt': 'Portuguese', 'tr': 'Turkish',
    'hi': 'Hindi', 'ja': 'Japanese', 'th': 'Thai', 'ro': 'Romanian', 'ar': 'Arabic', 'sv': 'Swedish',
    'fi': 'Finnish', 'el': 'Greek', 'pl': 'Polish', 'tl': 'Tagalog', 'et': 'Estonian', 'ta': 'Tamil',
    'ca': 'Catalan', 'vi': 'Vietnamese', 'ur': 'Urdu', 'eu': 'Basque', 'ht': 'Haitian Creole', 'ko': 'Korean',
    'iw': 'Hebrew', 'da': 'Danish', 'te': 'Telugu', 'cs': 'Czech', 'zh': 'Chinese', 'fa': 'Persian',
    'lv': 'Latvian', 'bn': 'Bengali', 'kn': 'Kannada', 'sl': 'Slovenian', 'lt': 'Lithuanian', 'no': 'Norwegian',
    'sr': 'Serbian', 'gu': 'Gujarati', 'bg': 'Bulgarian', 'ka': 'Georgian', 'cy': 'Welsh', 'is': 'Icelandic',
    'mr': 'Marathi', 'hu': 'Hungarian', 'ml': 'Malayalam', 'km': 'Khmer', 'ne': 'Nepali', 'hy': 'Armenian', 'my': 'Burmese'}


df_later['language_full'] = df_later['language'].map(lang_map)
lang_counts = (df_later.groupby(['language', 'language_full']).size().reset_index(name='count').sort_values(by='count', ascending=False))
lang_counts['proportion(%)'] = (lang_counts['count'] / lang_counts['count'].sum() * 100).round(2)
lang_counts

   language   language_full  count  proportion(%)
9        en         English   6256          54.79
10       es         Spanish   1121           9.82
51      und       Undefined    886           7.76
7        de          German    697           6.10
15       fr          French    600           5.25
23       it         Italian    417           3.65
50       uk       Ukrainian    151           1.32
41       ru         Russian    107           0.94
21       in      Indonesian    103           0.90
36       nl           Dutch     97           0.85
39       pt      Portuguese     83           0.73
49       tr         Turkish     80           0.70
17       hi           Hindi     65           0.57
25       ja        Japanese     64           0.56
47       th            Thai     47           0.41
40       ro        Romanian     45           0.39
44       sv         Swedish     35           0.31
0        ar          Arabic     35           0.31
14       fi         Finnish     34           0.30
8        el           Greek     33           0.29
38       pl          Polish     32           0.28
48       tl         Tagalog     31           0.27
11       et        Estonian     30           0.26
45       ta           Tamil     25           0.22
3        ca         Catalan     24           0.21
53       vi      Vietnamese     24           0.21
12       eu          Basque     22           0.19
52       ur            Urdu     22           0.19
18       ht  Haitian Creole     21           0.18
29       ko          Korean     19           0.17
24       iw          Hebrew     19           0.17
6        da          Danish     17           0.15
4        cs           Czech     16           0.14
46       te          Telugu     16           0.14
31       lv         Latvian     15           0.13
54       zh         Chinese     15           0.13
13       fa         Persian     15           0.13
2        bn         Bengali     14           0.12
28       kn         Kannada     11           0.10
42       sl       Slovenian     10           0.09
30       lt      Lithuanian      8           0.07
37       no       Norwegian      7           0.06
43       sr         Serbian      7           0.06
16       gu        Gujarati      7           0.06
1        bg       Bulgarian      6           0.05
26       ka        Georgian      6           0.05
5        cy           Welsh      5           0.04
22       is       Icelandic      5           0.04
19       hu       Hungarian      3           0.03
33       mr         Marathi      3           0.03
32       ml       Malayalam      2           0.02
27       km           Khmer      2           0.02
35       ne          Nepali      2           0.02
20       hy        Armenian      1           0.01
34       my         Burmese      1           0.01

# **3. Sentiment Analysis**

### **3.1 Sentiment Classification Pipeline**

In [ ]:
from transformers import pipeline

sentiment_model = pipeline(
    "sentiment-analysis",
    model="cardiffnlp/twitter-xlm-roberta-base-sentiment",
    device=0)

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

XLMRobertaForSequenceClassification LOAD REPORT from: cardiffnlp/twitter-xlm-roberta-base-sentiment
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [ ]:
texts = df_later['clean_text'].astype(str).str.slice(0,512).tolist()

def get_sentiment_batch(texts, batch_size=32):
    results = []

    for i in range(0, len(texts), batch_size):
        batch = texts[i:i+batch_size]
        batch_results = sentiment_model(batch)
        results.extend(batch_results)

    return results

sentiment_results = get_sentiment_batch(texts, batch_size=32)

sentiments = []
sent_scores = []

for result in sentiment_results:
    sentiments.append(result['label'])
    sent_scores.append(result['score'])

df_later['sentiment'] = sentiments
df_later['sentiment_score'] = sent_scores
df_later[['clean_text','sentiment','sentiment_score']].head(10)

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

,clean_text,sentiment,sentiment_score
0,lukraine et la russie présentent cette semaine...,negative,0.687747
1,i had the pleasure of talking to national secu...,positive,0.390932
2,possible consequences of kosovo amp serbia ten...,negative,0.755481
3,twitter facebook metaverse trump joebiden usa ...,negative,0.523891
4,if you are still having issues withdrawing you...,negative,0.681344
5,today ukraine missile destroy russian target f...,negative,0.769681
6,em outubro zelensky afirmou que os russos tinh...,negative,0.941974
7,swedish national day and the forest may not be...,negative,0.679428
8,antwort auf dpachef die dpa meldet um uhr un n...,neutral,0.555895
9,reminder to all our vatniks and russia support...,negative,0.697410

### **3.2 Sentiment Summary**

In [ ]:
sentiment_summary = (df_later['sentiment'].value_counts().reset_index())
sentiment_summary['proportion(%)'] = (sentiment_summary['count'] / sentiment_summary['count'].sum() * 100).round(2)

sentiment_summary

  sentiment  count  proportion(%)
0  negative   7835          68.61
1   neutral   2490          21.81
2  positive   1094           9.58

# **4. Emotion Analysis**

### **4.1 Emotion Classification Pipeline**

In [ ]:
emotion_model = pipeline(
    "zero-shot-classification",
    model="MoritzLaurer/mDeBERTa-v3-base-xnli-multilingual-nli-2mil7",
    device=0)

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

DebertaV2ForSequenceClassification LOAD REPORT from: MoritzLaurer/mDeBERTa-v3-base-xnli-multilingual-nli-2mil7
Key                             | Status     |  |
--------------------------------+------------+--+-
deberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [ ]:
candidate_labels = ["joy", "sadness", "anger", "fear", "love", "surprise"]

def get_emotions_batch(texts, batch_size=64):
    results = []

    for i in range(0, len(texts), batch_size):
        batch = texts[i:i+batch_size]
        outputs = emotion_model(batch, candidate_labels)
        results.extend(outputs)

    return results

emotion_results = get_emotions_batch(texts, batch_size=64)

emotions = []
emotion_scores = []

for result in emotion_results:
    emotions.append(result['labels'][0])
    emotion_scores.append(result['scores'][0])

df_later['emotion'] = emotions
df_later['emotion_score'] = emotion_scores
df_later[['clean_text', 'emotion', 'emotion_score']].head(10)

                                          clean_text   emotion  emotion_score
0  lukraine et la russie présentent cette semaine...      fear       0.313559
1  i had the pleasure of talking to national secu...       joy       0.893244
2  possible consequences of kosovo amp serbia ten...     anger       0.932377
3  twitter facebook metaverse trump joebiden usa ...       joy       0.802605
4  if you are still having issues withdrawing you...       joy       0.260309
5  today ukraine missile destroy russian target f...      fear       0.344813
6  em outubro zelensky afirmou que os russos tinh...     anger       0.454631
7  swedish national day and the forest may not be...  surprise       0.340780
8  antwort auf dpachef die dpa meldet um uhr un n...     anger       0.496938
9  reminder to all our vatniks and russia support...   sadness       0.478590

### **4.2 Emotion Summary**

In [ ]:
emotion_summary = (df_later['emotion'].value_counts().reset_index())
emotion_summary.columns = ['emotion', 'count']
emotion_summary['proportion(%)'] = (emotion_summary['count'] / emotion_summary['count'].sum() * 100).round(2)

emotion_summary

    emotion  count  proportion(%)
0     anger   5760          50.44
1  surprise   1668          14.61
2   sadness   1587          13.90
3      fear   1238          10.84
4       joy    972           8.51
5      love    194           1.70

# **5. Save Clean Data**

In [ ]:
clean_dataset = ['text', 'clean_text', 'language', 'language_full', 'sentiment', 'sentiment_score', 'emotion', 'emotion_score', 'timestamp', 'date', 'hour', 'tweetcreatedts', 'retweetcount', 'favorite_count', 'hashtags', 'phase']

df_later[clean_dataset].to_csv("/content/drive/My Drive/Major Project/clean_later_war_dataset.csv", index=False)

# **6. Import Clean Data**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

file_path = "/content/drive/My Drive/Major Project/clean_later_war_dataset.csv"
df_later = pd.read_csv(file_path)

Mounted at /content/drive

In [ ]:
df_later

,text,clean_text,language,language_full,sentiment,sentiment_score,emotion,emotion_score,timestamp,date,hour,tweetcreatedts,retweetcount,favorite_count,hashtags,phase
0,L'#Ukraine et la #Russie présentent cette sema...,lukraine et la russie présentent cette semaine...,fr,French,negative,0.687747,fear,0.313559,2023-06-07 00:23:08.483217,2023-06-07,0,2023-06-07 00:00:06,0,2,"[{'text': 'Ukraine', 'indices': [2, 10]}, {'te...",Later War
1,I had the pleasure of talking to National Secu...,i had the pleasure of talking to national secu...,en,English,positive,0.390932,joy,0.893244,2023-06-07 00:23:08.478047,2023-06-07,0,2023-06-07 00:00:08,0,0,"[{'text': 'Kakhovka', 'indices': [85, 94]}, {'...",Later War
2,Possible Consequences of Kosovo &amp; Serbia T...,possible consequences of kosovo amp serbia ten...,ca,Catalan,negative,0.755481,anger,0.932377,2023-06-07 00:23:08.472855,2023-06-07,0,2023-06-07 00:00:30,0,0,"[{'text': 'Russia', 'indices': [54, 61]}, {'te...",Later War
3,https://t.co/qMZLQEQWjs\nhttps://t.co/TfXdd1Kp...,twitter facebook metaverse trump joebiden usa ...,und,Undefined,negative,0.523891,joy,0.802605,2023-06-07 00:23:08.467704,2023-06-07,0,2023-06-07 00:00:33,0,0,"[{'text': 'twitter', 'indices': [73, 81]}, {'t...",Later War
4,if you are still having issues withdrawing you...,if you are still having issues withdrawing you...,en,English,negative,0.681344,joy,0.260309,2023-06-07 00:23:08.462562,2023-06-07,0,2023-06-07 00:00:55,0,0,"[{'text': 'kicurency', 'indices': [109, 119]},...",Later War
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11414,"El Primer Ministro de #Cuba, @MMarreroCruz, en...",el primer ministro de cuba encabeza la delegac...,es,Spanish,neutral,0.823303,surprise,0.249811,2023-06-08 00:09:47.759713,2023-06-08,0,2023-06-07 23:59:46,31,0,"[{'text': 'Cuba', 'indices': [22, 27]}, {'text...",Later War
11415,🇨🇺🇧🇪/Una postura de condena al bloqueo de #Est...,una postura de condena al bloqueo de estadosun...,es,Spanish,negative,0.468992,anger,0.642855,2023-06-08 00:09:47.731907,2023-06-08,0,2023-06-07 23:59:50,154,0,"[{'text': 'EstadosUnidos', 'indices': [42, 56]...",Later War
11416,#Kherson sott’acqua dopo l’esplosione della di...,kherson sottacqua dopo lesplosione della diga ...,it,Italian,negative,0.912173,anger,0.256773,2023-06-08 00:09:47.720803,2023-06-08,0,2023-06-07 23:59:51,102,0,"[{'text': 'Kherson', 'indices': [0, 8]}, {'tex...",Later War
11417,Why is a so-called #labor government in #Austr...,why is a socalled labor government in australi...,en,English,negative,0.924965,surprise,0.380496,2023-06-08 02:33:35.776122,2023-06-08,2,2023-06-07 23:59:57,0,0,"[{'text': 'labor', 'indices': [19, 25]}, {'tex...",Later War
11418,#HéroesDeLaSalud\n#CubaPorLaVida #Cuba @cubaco...,héroesdelasalud cubaporlavida cuba,und,Undefined,positive,0.447781,joy,0.341330,2023-06-08 00:09:47.664898,2023-06-08,0,2023-06-07 23:59:58,80,0,"[{'text': 'HéroesDeLaSalud', 'indices': [0, 16...",Later War